name = "mouse-archive-upload"
main = "worker.js"
compatibility_date = "2025-11-22"
type = "javascript"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true

[[r2_buckets]]
binding = "FILES"
bucket_name = "mouse-archive-files"

[env.production]
workers_dev = false
route = ""
zone_id = ""
